# This is a basic workflow to help you get started with Actions

name: DevBranchAction

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Try Run Matermost chat
      - name: Create Mattermost chat
        run: |
          echo "{\"text\":\"### Have new feature on Development :deployparrot: \"}" > mattermost.json
      - uses: mattermost/action-mattermost-notify@master
        env: 
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          MATTERMOST_CHANNEL: Community
          MATTERMOST_USERNAME: "@wazeer"
